
POST http://localhost:4000/addEvent/Social
Content-Type: application/json

{
    "title": "Blood Donation Camp",
    "description": "Save life of other person by donating the blood",
    "eventDate": "on 17-01-2024",
    "eventTime": "11 AM",
    "eventLocation": "Auditorium",
    "dateString": "17012024",
    "imgUrl": "https://www.careinsurance.com/upload_master/media/posts/June2020/IQKrrYI3nqo0i9PNqO7W.jpg"
}
###

GET http://localhost:4000/events/Social

###
POST http://localhost:4000/register/
Content-Type: application/json

{
    "username": "user1",
    "email": "user1@gmail.com",
    "password": "123456"
}

###
DELETE http://localhost:5000/logout 
Content-Type: application/json

{
    "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Implc3RAZ21haWwuY29tIiwiaWF0IjoxNzA2Nzc2ODI0fQ.ouHGRRWMmPLIbFNCalE2SQ4B1Q_4t7iES68-d5oYtOs"
}

###
GET http://localhost:4000/sign-in
Authorization: BEARER eyJhbGciOiJIUzI1NiJ9.dXNlcjFAZ21haWwuY29t.tTSjtacYPVkE70Rv4-jRndV777aK-pqkdO6lCeTmdx4
###

POST http://localhost:4000/sign-in
Content-Type: application/json



###
POST http://localhost:5000/token 
Content-Type: application/json

{
    "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhhcnVuQGdtYWlsLmNvbSIsImlhdCI6MTcwNjc3Njk2N30.gcF8vx7kSK_IAqrIj4cnyNNp8VonrKqAxQ-cBd9ybxM"
}